### ISSUE TITLE
Elasticsearch as Performance Data Backend

### ISSUE THREAD

**Issue by duylong** [statusengine/worker#1]
Hi,

I use already Elasticsearch with Grafana. Elasticsearch can also accept time series. 
It would be interesting to add Elasticsearch as backend.

**Comment by duylong** [comment]
The most important in Elasticsearch for the timeseries is the mapping. You can see a example here: https://www.elastic.co/blog/elasticsearch-as-a-time-series-data-store

The best is to define your own fields, create indices by day and consume data in using the scroll method.

If you need more explanations, I can help you :)

**Comment by nook24** [comment]
Hi @duylong, if you could help me creating the mapping, would be great.
I struggle with how to save `hostname`, `service_description`and `metric` and fields like this the bast at Elasticsearch...
Even it should be compatible with the Grafana Plugin^^

**Comment by duylong** [comment]
Example mapping:

```
{
        "template" : "statusengine-*",
        "order" : 0,
        "settings" : {
                "index" : {
                        "number_of_shards" : 1,
                        "refresh_interval" : "60s",
                        "codec": "best_compression",
                        "mapper.dynamic": false
                }
        },
        "mappings" : {
                "_default_": {
                        "_all": { "enabled": "false" },
                        "_source" : { "enabled" : "true" }
                },
                "metric" : {
                        "properties": {
                                "@timestamp": {
                                        "type": "date"
                                },
                                "metric": {
                                        "type": "double",
                                        "index": "no"
                                },
                                "hostname": {
                                        "type": "string",
                                        "index": "not_analyzed"
                                },
                                "service_description": {
                                        "type": "string",
                                        "index": "not_analyzed"
                                }
                       }
                }
        }
}
```

Example index name: 
```
statuengine-2017.06 (storage by month) or statuengine-2017.08.19 (storage by day)
```

**Comment by nook24** [comment]
@duylong many thanks, hopefully i will find some spare time to implement this :)

**Comment by duylong** [comment]
I remain available if necessary ;)

**Comment by nook24** [comment]
So, i created a new Branch: https://github.com/statusengine/worker/tree/elastic with the first steps for Elasticsearch, you can test...
For ES5 you need PHP >= 5.6. After you cloned the branch, you need to execute `composer install` or `composer update` to load the new dependencies.

The mapping is defined at: https://github.com/statusengine/worker/tree/elastic/lib/Elasticsearch
Don't miss the new config options: https://github.com/statusengine/worker/blob/elastic/etc/config.yml.example#L154-L161

I was able to save some data to ES:
<img width="738" alt="bildschirmfoto 2017-09-06 um 23 20 08" src="https://user-images.githubusercontent.com/9019992/30135353-b50bc0ca-935a-11e7-9519-a5f4732f37e7.png">
But i have no idea how to query the data - I tried with Grafana but this failed hard :D

**Comment by duylong** [comment]
For the elasticsearch config, the best choice is: 
```
elasticsearch_index: statusengine-metric- => 

elasticsearch_index: [statusengine-metric-]YYYY-MM-dd
elasticsearch_pattern: daily

or

elasticsearch_index: statusengine-metric
elasticsearch_pattern: none
```

No problem, I have PHP7 for testing :)

For using with Grafana, you create a data source. For your example:

```
Http settings:
    url: http://127.0.0.1:9200
    access: direct
Elasticsearch details
    index name: statusengine-metric-
    pattern: no pattern
    time field name: @timestamp
    version: 5.x
```
Save and test :)

For query in Grafana, create a graph panel with this example:
```
Query: hostname:$Host AND service_description:$Service
Metric: "Sum" with value "metric"
```

$Host and $Service are variables defined in templating. For example with $Host:
```
{"find": "terms", "field": "hostname", "size": 1000}
```

**Comment by duylong** [comment]
The "metric" attribute is a value or a string ??? if metric is a string (from your code), you must change the mapping:

```
                                "value": {
                                        "type": "double",
                                        "index": "no"
                                },
                                "metric": {
                                        "type": "string",
                                        "index": "not_analyzed"
                                },
```
In Grafana: "Sum" with value "value"

**Comment by nook24** [comment]
If i use a syntax like
````elasticsearch_index: [statusengine-metric-]YYYY-MM-dd````
in the Statusengine Worker config, does Elasticsearch do the dirty job for me and create the index with the current date, or do i need to create the index by my self?

I sill have the issue, that my Grafana don't want to show any data:
<img width="1435" alt="bildschirmfoto 2017-09-07 um 18 30 03" src="https://user-images.githubusercontent.com/9019992/30178320-c964bc8a-9408-11e7-876e-6c3d4fbf88af.png">
I tried it without creating an template. Could this be the issue?

How ever, i implemented the first basic client for Elasticsearch to the Statusengine Ui, to check if my data looks like expected:
<img width="1350" alt="bildschirmfoto 2017-09-07 um 19 55 40" src="https://user-images.githubusercontent.com/9019992/30178378-fe2751f8-9408-11e7-8392-309fcc1e51f9.png">
Looks not to bad i think :)
Code at: https://github.com/statusengine/interface/tree/elastic

Thinks to do:
- Create index automatically (If required?)
- Create the template if missing automatically
- Delete old data via the Statusengine Cron

Does the interface need to query multiple indices at midnight?

**Comment by duylong** [comment]
Good job !

You must to query multiples indices when you are between multiple periods of time. Use scroll method when you are multiples indices, it's more fast in order to load metrics.

- The index creation is not required
- You should add a option for manage template (load a custom template, template replacement...), for exemple: template (path), template_name (string), template_overwrite (bool)
- Delete old data is easy, just delete the old daily index

Your date field is "@timestamp" or "timestamp" ? code is "timestamp", mapping is "@timestamp". This may be why grafana does not work.

**Comment by nook24** [comment]
Ah, good hint with **@timestamp**. I renamed all timestamps to @timestamp and now also Grafana is working:
<img width="1436" alt="bildschirmfoto 2017-09-08 um 18 42 47" src="https://user-images.githubusercontent.com/9019992/30222039-fdcbe620-94c5-11e7-9e50-244d329b5cdd.png">

Does it make much sense, to give the user the option to change the template? I don't know if there is a use case for, or just an option to break the application...

Looking forward to finish this over the weekend [hopefully :)]

**Comment by duylong** [comment]
Some people will probably want to personalize the number of shards, disable the "_source" to save disk space, change algorithm compression... However you can overload the template, it is not a priority addition, I know you will be asked for a day ;)

You are doing well in the implementation :)

**Comment by nook24** [comment]
I guess the implementation at the SE Worker is almost done.
These are the new config options:
````YML
# Statusengine will create an index template to store performance data to
# Elasticsearch.
# The template is hardcoded and will be managed by Statusengine
# automatically. How ever, you can still change
# important settings.
# If you change any template settings, you need to do this
# BEFORE THE FIRST start of Statusengine Worker,
# or you need to delete/edit the old template manually via Elasticsearch API
elasticsearch_template:
  name: statusengine-metric
  number_of_shards: 2
  number_of_replicas: 0
  refresh_interval: 15s
  codec: best_compression
  enable_all: 0
  enable_source: 1

# Index that will be used to store data in Elasticsearch
elasticsearch_index: statusengine-metric-

# The value of elasticsearch_pattern will be added to the end of your
# defiend elasticsearch_index. It is recommended to terminate
# your elasticsearch_index with an dash, like the example
# index: statusengine-metric-
#
# Available patterns:
# - none     => All data in one index, this will also disable the data clenup for Elasticsearch
# - daily    => statusengine-metric-YYYY.MM.DD
# - weekly   => statusengine-metric-GGGG.WW
# - monthly  => statusengine-metric-YYYY.MM
elasticsearch_pattern: daily

# Set the ip address or hostname for your Elasticsearch system or cluster
# Statusengine will use the HTTP API
elasticsearch_address: 127.0.0.1

# Port where your Elasticsearch server is listening to
elasticsearch_port: 9200
````
Don't miss to update your config, otherwise the default values will be used...

Now Statusengine Worker will do:
- Create the index template if missing
- Insert Nagios/Naemon performance data to given Elasticsearch index
- _Rotate_ index by given pattern
- Delete old indices (as defined by `age_perfdata`)

One quick question about the pattern. I looked at Grafana to get the values , people are used to.
`daily` and `monthly` is clear for me:
````
daily => statusengine-metric-2017.09.10
monthly => statusengine-metric-2017.09
````
But I have no idea about the `weekly` value `GGGG.WW`

What is G and W in a date? Java docs say G is `Era designator` and PHP docs say G is `24-hour format of an hour without leading zeros`. Both will not match to four digits.
As fallback I used the Year and the ISO-8601 week number of year, don't know if this is right or not...
Example: `statusengine-metric-2017.36`

In the next step I will update the Interface, to be able to handle multiple indices.
